spring:
  application:
    name: umc-10th

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:abcdefghijklmnopqrstuvwxyz1234567890abcdef}
  access-token-validity-in-ms: 3600000

oauth:
  kakao:
    user-info-uri: https://kapi.kakao.com/v2/user/me