spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc10th
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  token:
    secretKey: "this-is-secret-key-this-is-secret-key-this-is-secret-key"
    expiration:
      access: 1800000